site_url: http://localhost:3000
# site_url: https://github.com/r4nd3l/Nuxt3
logo_url: https://raw.githubusercontent.com/r4nd3l/Nuxt3/feature/netlify/public/img/myLogo.png

# The search functionally requires loading all collection(s) entries,
search: true

publish_mode: editorial_workflow
backend:
  name: github
  # name: test-repo # in development mode(!)
  repo: themattmiller88/Nuxt3Netlify
  branch: feature/netlify
  squash_merges: true

# used together with `npx netlify-cms-proxy-server`. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

media_folder: "/assets/images"
public_folder: "/public/img"

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  # page - Main
  - name: "main"
    # preview_path: "blog/{{year}}/{{month}}/{{slug}}"
    label: "Main"
    description: The main collection
    label_singular: "Main"
    folder: "/content/01.main"
    create: true
    format: "frontmatter"
    editor:
      preview: true
    fields:
      - { label: "Created Date", name: "createdAt", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Button", name: "button", widget: "string", required: true }

  # page - Home
  - name: "home"
    label: "Home"
    description: The home collection
    label_singular: "Home"
    folder: "/content/02.home"
    create: true
    format: "frontmatter"
    slug: "{{fields.createdAt}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Created Date", name: "createdAt", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }

  # page - About
  - name: "about"
    label: "About"
    description: The about collection
    label_singular: "About"
    folder: "/content/03.about"
    create: true
    format: "frontmatter"
    slug: "{{slug}}"
    preview_path: "projects/{{slug}}"
    fields:
      - {
          label: "Project Category",
          name: "category",
          widget: "select",
          default: "animals",
          options: [{ label: "Animals", value: "animals" }, { label: "Food", value: "food" }],
        }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Cover Image", name: "cover", widget: "image", required: false, allow_multiple: false }
      - { label: "Content", name: "body", widget: "markdown", required: false }
      - {
          label: "Gallery",
          name: "gallery",
          widget: "list",
          required: false,
          summary: "{{fields.image}}",
          field: { label: "Image", name: "image", widget: "image" },
        }

  # page - Single
  - name: "single"
    label: "Single"
    description: The single collection
    label_singular: "Single"
    folder: "/content/04.single"
    create: true
    format: "frontmatter"
    editor:
      preview: true
    fields:
      - { label: "Created Date", name: "createdAt", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Button", name: "button", widget: "string", required: true }

  # page - Footer
  - name: "footer"
    label: "Footer"
    description: The footer collection
    label_singular: "Footer"
    folder: "/content/_partials/footer"
    create: true
    format: "frontmatter"
    editor:
      preview: true
    fields:
      - { label: "Created Date", name: "createdAt", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Body", name: "body", widget: "markdown", required: false }
